const areaData = [
  {
    area: "Kasarani",
    campus: "USIU/KU",
    tier: "Satellite",
    baseRent: 8500,
    minRent: 5500,
    maxRent: 12000,
    matatuFare: 50,
    avgWalk: 20,
    valueScore: 56.1,
    mapX: 64,
    mapY: 24,
    lat: -1.2217,
    lng: 36.8976,
    vibe: "Busy, flexible, practical",
    note: "Flexible for USIU and KU students, but total burn climbs once transport and utilities stack up.",
    gallery: ["street", "room", "route"]
  },
  {
    area: "Ngong Road",
    campus: "Strathmore",
    tier: "Mid",
    baseRent: 11000,
    minRent: 7500,
    maxRent: 15000,
    matatuFare: 70,
    avgWalk: 14,
    valueScore: 49.3,
    mapX: 38,
    mapY: 71,
    lat: -1.3002,
    lng: 36.7858,
    vibe: "Convenient, premium, fast",
    note: "Closer access to Strathmore, but you pay the proximity premium.",
    gallery: ["compound", "room", "route"]
  },
  {
    area: "Ngara",
    campus: "UoN/TUK",
    tier: "Inner City",
    baseRent: 7000,
    minRent: 4000,
    maxRent: 10000,
    matatuFare: 30,
    avgWalk: 19,
    valueScore: 64.7,
    mapX: 48,
    mapY: 42,
    lat: -1.2715,
    lng: 36.8219,
    vibe: "Central, connected, efficient",
    note: "Short matatu fare and strong UoN/TUK access make it one of the smartest central picks.",
    gallery: ["street", "route", "room"]
  },
  {
    area: "South B",
    campus: "KCA",
    tier: "Mid",
    baseRent: 9500,
    minRent: 6500,
    maxRent: 13000,
    matatuFare: 60,
    avgWalk: 18,
    valueScore: 52.7,
    mapX: 55,
    mapY: 67,
    lat: -1.3087,
    lng: 36.8469,
    vibe: "Balanced, residential, steady",
    note: "Comfortable mid-tier option for KCA students who can stretch beyond the low-cost bracket.",
    gallery: ["compound", "street", "route"]
  },
  {
    area: "South C",
    campus: "KCA",
    tier: "Mid",
    baseRent: 9000,
    minRent: 6000,
    maxRent: 13000,
    matatuFare: 60,
    avgWalk: 17,
    valueScore: 53.2,
    mapX: 50,
    mapY: 63,
    lat: -1.3194,
    lng: 36.8126,
    vibe: "Accessible, calmer, balanced",
    note: "Balances commute and comfort, but not the cheapest route for a tight allowance.",
    gallery: ["compound", "room", "route"]
  },
  {
    area: "Parklands",
    campus: "UoN/TUK",
    tier: "Mid",
    baseRent: 10500,
    minRent: 7500,
    maxRent: 15000,
    matatuFare: 40,
    avgWalk: 15,
    valueScore: 50.4,
    mapX: 44,
    mapY: 35,
    lat: -1.2632,
    lng: 36.8098,
    vibe: "Premium, close, polished",
    note: "Premium access zone with decent transport, but one of the pricier choices in the dataset.",
    gallery: ["street", "compound", "room"]
  },
  {
    area: "Kahawa West",
    campus: "KU/MKU",
    tier: "Satellite",
    baseRent: 6500,
    minRent: 3000,
    maxRent: 9000,
    matatuFare: 30,
    avgWalk: 22,
    valueScore: 72.8,
    mapX: 60,
    mapY: 12,
    lat: -1.1835,
    lng: 36.9261,
    vibe: "Comrade-heavy, efficient, strong value",
    note: "Top value area in the notebook thanks to lower rent, strong private-meter share, and KU/MKU access.",
    gallery: ["room", "route", "street"]
  },
  {
    area: "Roysambu",
    campus: "USIU/KU",
    tier: "Satellite",
    baseRent: 7500,
    minRent: 4500,
    maxRent: 10500,
    matatuFare: 40,
    avgWalk: 20,
    valueScore: 58.6,
    mapX: 56,
    mapY: 21,
    lat: -1.2108,
    lng: 36.8875,
    vibe: "Connected, practical, commuter-friendly",
    note: "Good for USIU and KU students who want commuter convenience without Parklands prices.",
    gallery: ["route", "street", "room"]
  },
  {
    area: "Zimmerman",
    campus: "KU",
    tier: "Satellite",
    baseRent: 5500,
    minRent: 3000,
    maxRent: 8000,
    matatuFare: 40,
    avgWalk: 24,
    valueScore: 60.4,
    mapX: 58,
    mapY: 17,
    lat: -1.2053,
    lng: 36.8846,
    vibe: "Affordable, social, student-first",
    note: "Cheapest median rent in the findings and one of the strongest choices for students who need serious value.",
    gallery: ["room", "compound", "route"]
  },
  {
    area: "Thika Road",
    campus: "MKU/KU",
    tier: "Satellite",
    baseRent: 7000,
    minRent: 4000,
    maxRent: 10000,
    matatuFare: 50,
    avgWalk: 22,
    valueScore: 63.1,
    mapX: 70,
    mapY: 16,
    lat: -1.218,
    lng: 36.9135,
    vibe: "Direct, mobile, lower-burn",
    note: "Solid middle-ground pick when you want lower rent but still want direct road links.",
    gallery: ["route", "street", "room"]
  },
  {
    area: "Ruaka",
    campus: "USIU",
    tier: "Satellite",
    baseRent: 9000,
    minRent: 5500,
    maxRent: 13000,
    matatuFare: 70,
    avgWalk: 18,
    valueScore: 51.7,
    mapX: 35,
    mapY: 19,
    lat: -1.2101,
    lng: 36.7892,
    vibe: "Popular, lively, pricier",
    note: "Popular for USIU students, but transport and rent can push monthly burn up quickly.",
    gallery: ["street", "compound", "route"]
  },
  {
    area: "Dagoretti",
    campus: "Strathmore",
    tier: "Mid",
    baseRent: 8000,
    minRent: 5000,
    maxRent: 11000,
    matatuFare: 60,
    avgWalk: 21,
    valueScore: 55.9,
    mapX: 30,
    mapY: 58,
    lat: -1.2837,
    lng: 36.7442,
    vibe: "Lower-entry, connected, sensible",
    note: "Useful for Strathmore students who want a lower entry point than Ngong Road.",
    gallery: ["street", "room", "route"]
  },
  {
    area: "Langata",
    campus: "Daystar",
    tier: "Mid",
    baseRent: 8500,
    minRent: 5000,
    maxRent: 12000,
    matatuFare: 70,
    avgWalk: 19,
    valueScore: 54.2,
    mapX: 42,
    mapY: 84,
    lat: -1.3622,
    lng: 36.7443,
    vibe: "Spread out, campus-linked, moderate",
    note: "Makes sense for Daystar access, but keep an eye on transport cost every month.",
    gallery: ["route", "street", "compound"]
  },
  {
    area: "Embakasi",
    campus: "KCA",
    tier: "Satellite",
    baseRent: 6000,
    minRent: 3000,
    maxRent: 9000,
    matatuFare: 50,
    avgWalk: 23,
    valueScore: 67.4,
    mapX: 80,
    mapY: 55,
    lat: -1.3156,
    lng: 36.8941,
    vibe: "Value-heavy, expanding, commuter-smart",
    note: "Strong KCA value zone with lower rent and dependable links along Airport Road.",
    gallery: ["street", "room", "route"]
  }
];

const rankings = [
  { rank: 1, area: "Kahawa West", score: 72.8, medianRent: 6500, burn: 14720, reason: "Closest KU and MKU access with high private-meter share." },
  { rank: 2, area: "Embakasi", score: 67.4, medianRent: 6500, burn: 15600, reason: "KCA-friendly and cheaper than many mid-tier alternatives." },
  { rank: 3, area: "Ngara", score: 64.7, medianRent: 7500, burn: 15720, reason: "Best inner-city value with the lowest common matatu fare." },
  { rank: 4, area: "Thika Road", score: 63.1, medianRent: 6500, burn: 15600, reason: "Lower monthly burn and good road access for KU and MKU students." },
  { rank: 5, area: "Zimmerman", score: 60.4, medianRent: 5500, burn: 14160, reason: "Cheapest median rent and a strong comrade-friendly zone." }
];

const insights = [
  { number: "01", title: "The KPLC meter is a hidden tax", body: "A shared meter costs about KES 600 more per month than a private one. Across a four-year degree, that becomes roughly KES 28,800." },
  { number: "02", title: "Cheap rent can still mean expensive living", body: "Transport, utilities, and distance can erase what looked like a saving. Always compare full monthly burn." },
  { number: "03", title: "Closer to campus usually costs more", body: "The notebook found about KES 700 added to monthly rent for every 10 minutes closer to campus." }
];

const checklist = [
  "Ask whether the KPLC meter is private or shared.",
  "Test taps and confirm water really works as promised.",
  "Check phone signal inside the room for online classes and calls.",
  "Walk the actual route to campus and time it yourself.",
  "Get written proof for deposit and first month rent.",
  "Talk to one current tenant before signing.",
  "Photograph every room on move-in day.",
  "Confirm matatu stage, route, and actual fare."
];

const redFlags = [
  "Someone asks for a viewing fee before showing the room.",
  "The landlord wants deposit before you physically visit.",
  "The photos look too perfect and cannot be verified.",
  "There are no visible tenants or activity in the compound."
];

const budgetBands = [
  { budget: "KES 10,000", zones: "Zimmerman, Kahawa West, Embakasi", rent: "KES 4,000 to 5,000", note: "Only the value-heavy zones keep this comfortable." },
  { budget: "KES 15,000", zones: "Ngara, Roysambu, Thika Road", rent: "KES 6,000 to 7,500", note: "Enough room to balance commute and a decent space." },
  { budget: "KES 20,000", zones: "Kasarani, South B, Dagoretti", rent: "KES 8,000 to 10,000", note: "A more flexible tier if you want comfort without going premium." },
  { budget: "KES 25,000+", zones: "Parklands, Ngong Road, South C", rent: "KES 10,000 to 13,000", note: "This is where proximity and convenience start dominating." }
];

const roomAdjustments = {
  single: { label: "Single room", delta: -1500 },
  bedsitter: { label: "Bedsitter", delta: 0 },
  studio: { label: "Studio", delta: 1000 },
  ensuite: { label: "En suite bedsitter", delta: 2000 }
};

const budgetGuides = {
  10000: "Try to keep rent below KES 5,000",
  15000: "Try to keep rent below KES 7,500",
  20000: "Try to keep rent below KES 10,000",
  25000: "Try to keep rent below KES 13,000"
};
